-- Mom's 70th (koji_trips.id = 6): copy pass and flight change, applied live 2026-09-15.
-- Opinionated filler removed; each stop keeps what the place is, why it was chosen,
-- and the practical detail. Nathan & Dez now fly UA14 EWR-LHR (7:15 PM / 7:15 AM).
begin;

-- flight change
update koji_logistics set value_md = $q$UA14 - Thu, Oct 15 - EWR to LHR - Departs 7:15 PM - Arrives 7:15 AM$q$ where id = 113;
update koji_stops set time_label = '7:15pm', sort_order = 40, body_md = $q$United 14, nonstop from Newark at **7:15pm**, landing at Heathrow **7:15am** Friday, five minutes after Mom.$q$ where id = 485;
update koji_stops set body_md = $q$Virgin Atlantic 8, nonstop from LAX at **3:50pm**, landing at Heathrow **10:15am** Friday.$q$ where id = 486;
update koji_stops set body_md = $q$Delta 16, nonstop from Detroit at **6:40pm**, landing at Heathrow **7:10am** Friday. Nathan and Dez land five minutes later; Marshall and Francesca at 10:15am. The arrival-morning plan is in Logistics.$q$ where id = 487;
update koji_logistics set value_md = $q$Everyone lands Fri Oct 16 - Mom 7:10am (Delta), Nathan & Dez 7:15am (United), Marshall & Francesca 10:15am (Virgin Atlantic). Straight to the Cotswolds from Heathrow; the drive west skips London entirely (~1h45). The first three wait for Marshall and Francesca at [Heathrow](https://www.google.com/maps/search/?api=1&query=Heathrow+Airport+London) arrivals, and all five leave together around 11am.$q$ where id = 111;
update koji_logistics set value_md = $q$Everyone flies home Sun Oct 25 - Mom departs 11:20am (at the airport by ~8:20am, out of the hotel by ~7:45am), Nathan & Dez 3:20pm (at the airport by ~12:20pm), Marshall & Francesca 5:05pm (~2:00pm). Mom's early flight is why the trip ends in London rather than the Cotswolds.$q$ where id = 112;
update koji_logistics set value_md = $q$Book 2 of the 3 dinner options at each slot; cancelling one is easier than finding a table at 6pm.$q$ where id = 38;

-- day 2
update koji_stops set body_md = $q$Marshall and Francesca land last, at 10:15am. Collect bags, pick up the rental at a [Heathrow](https://www.google.com/maps/search/?api=1&query=Heathrow+Airport+car+rental) depot, and head west. The Cotswolds are about 1h45 by road and the route skips London. Without a car: Heathrow Express to [Paddington](https://www.google.com/maps/search/?api=1&query=Paddington+Station+London), a direct train to [Stroud](https://www.google.com/maps/search/?api=1&query=Stroud+Railway+Station) (~1h30), then a 10-minute taxi to the hotel.$q$ where id = 177;
update koji_stops set body_md = $q$Lunch at [Burleigh Court](https://www.google.com/maps/search/?api=1&query=Burleigh+Court+Hotel+Minchinhampton+Stroud) on arrival, or a pub in [Minchinhampton](https://www.google.com/maps/search/?api=1&query=Minchinhampton) or [Nailsworth](https://www.google.com/maps/search/?api=1&query=Nailsworth), both a few minutes from the hotel. [Jolly Nice Farmshop](https://www.google.com/maps/search/?api=1&query=Jolly+Nice+Farmshop+Frampton+Mansell) on the A419 is the quick stop on the way in.$q$ where id = 178;
update koji_stops set body_md = $q$Check in at [Burleigh Court Hotel](https://www.google.com/maps/search/?api=1&query=Burleigh+Court+Hotel+Minchinhampton+Stroud), a country house hotel near Minchinhampton on the southern edge of the Cotswolds. Cirencester is about 20 minutes away; Stow, Bourton, and the Slaughters are a 35 to 40 minute drive north. Ask about early rooms at lunch.$q$ where id = 179;
update koji_stops set body_md = $q$A light afternoon after the overnight flights: the hotel grounds, the lanes around [Minchinhampton Common](https://www.google.com/maps/search/?api=1&query=Minchinhampton+Common), tea, and a rest before dinner.$q$ where id = 180;
update koji_stops set body_md = $q$Dinner at [Burleigh Court](https://www.google.com/maps/search/?api=1&query=Burleigh+Court+Hotel+Minchinhampton+Stroud) the first night keeps everyone off the road and in bed early. Two alternatives if the group has the energy: [Prithvi](https://www.google.com/maps/search/?api=1&query=Prithvi+Cheltenham) in Cheltenham (about 30 minutes), a Michelin-starred modern Indian restaurant, and [The Woolpack](https://www.google.com/maps/search/?api=1&query=The+Woolpack+Inn+Slad) in Slad (about 15 minutes), the village pub Laurie Lee wrote about and drank in. *Reserve either way.*$q$ where id = 181;

-- day 3
update koji_stops set body_md = $q$Saturday mornings only, 10 minutes from the hotel. Stroud's market is one of the largest farmers' markets in the country, with dozens of stalls of local produce. Breakfast from the stalls and picnic supplies for the walk, then drive north. [Stroud Farmers' Market](https://www.google.com/maps/search/?api=1&query=Stroud+Farmers+Market).$q$ where id = 492;
update koji_stops set body_md = $q$5 to 6 miles, mostly flat, on a riverside path along the River Eye. Allow 3 hours with stops. Start in [Bourton-on-the-Water](https://www.google.com/maps/search/?api=1&query=Bourton-on-the-Water) (15 minutes from Stow) and park near the village green. The full self-guided route is in the Logistics tab.$q$ where id = 182;
update koji_stops set body_md = $q$A former manor house, now an inn, with a terrace on the River Eye in [Lower Slaughter](https://www.google.com/maps/search/?api=1&query=Lower+Slaughter). Open all day; drinks need no reservation. A 20-minute stop about a third of the way round. [The Slaughters Country Inn](https://www.google.com/maps/search/?api=1&query=The+Slaughters+Country+Inn).$q$ where id = 183;
update koji_stops set body_md = $q$[The Slaughters Country Inn](https://www.google.com/maps/search/?api=1&query=The+Slaughters+Country+Inn) (book ahead for lunch) or [The Mousetrap Inn](https://www.google.com/maps/search/?api=1&query=The+Mousetrap+Inn+Bourton+on+the+Water) back in Bourton. If a picnic suits the walk better, [D'Ambrosi](https://www.google.com/maps/search/?api=1&query=DAmbrosi+Fine+Foods+Stow-on-the-Wold) in Stow is a deli that packs picnic food; collect it before setting off.$q$ where id = 184;
update koji_stops set body_md = $q$Cirencester was Corinium, the second-largest town in Roman Britain. Park near the [Market Place](https://www.google.com/maps/search/?api=1&query=Market+Place+Cirencester). [Cirencester](https://www.google.com/maps/search/?api=1&query=Cirencester).$q$ where id = 185;
update koji_stops set body_md = $q$Roman mosaics from the town and the villas around it, in a museum built around the finds. About 75 minutes. [Corinium Museum](https://www.google.com/maps/search/?api=1&query=Corinium+Museum+Cirencester).$q$ where id = 186;
update koji_stops set body_md = $q$Independent shops along [Black Jack Street](https://www.google.com/maps/search/?api=1&query=Black+Jack+Street+Cirencester) and [Cricklade Street](https://www.google.com/maps/search/?api=1&query=Cricklade+Street+Cirencester), both just off the Market Place. Tea or coffee at [Made by Bob](https://www.google.com/maps/search/?api=1&query=Made+by+Bob+Cirencester) or [Jack's Coffee](https://www.google.com/maps/search/?api=1&query=Jacks+Coffee+Cirencester) before the drive back.$q$ where id = 187;
update koji_stops set body_md = $q$**Country house:** [The Wheatsheaf at Northleach](https://www.google.com/maps/search/?api=1&query=The+Wheatsheaf+Inn+Northleach), a coaching inn with a modern British menu and a fireplace. *Reservation required.*<br><br>**Village pubs:** [The Bull at Charlbury](https://www.google.com/maps/search/?api=1&query=The+Bull+Charlbury) or [The Bell at Sapperton](https://www.google.com/maps/search/?api=1&query=The+Bell+at+Sapperton). The Bull is owned by Jeremy Clarkson and Wade Ward; the Bell is the more traditional of the two. *Reservation required.*<br><br>**Indian:** [Prithvi](https://www.google.com/maps/search/?api=1&query=Prithvi+Cheltenham) in Cheltenham, Michelin-starred, if the first night went to the hotel instead. *Reservation required.*$q$ where id = 188;

-- day 4
update koji_stops set body_md = $q$An open Cotswolds day. Options: [Broadway](https://www.google.com/maps/search/?api=1&query=Broadway) and [Broadway Tower](https://www.google.com/maps/search/?api=1&query=Broadway+Tower+Worcestershire), an 18th-century folly on one of the highest points in the Cotswolds; [Chipping Campden](https://www.google.com/maps/search/?api=1&query=Chipping+Campden) with [Hidcote Manor Garden](https://www.google.com/maps/search/?api=1&query=Hidcote+Manor+Garden), an Arts and Crafts garden (check autumn hours); [Batsford Arboretum](https://www.google.com/maps/search/?api=1&query=Batsford+Arboretum+Moreton-in-Marsh) for October colour; [Burford](https://www.google.com/maps/search/?api=1&query=Burford) and its [St John the Baptist church](https://www.google.com/maps/search/?api=1&query=St+John+the+Baptist+Church+Burford); [Blenheim Palace](https://www.google.com/maps/search/?api=1&query=Blenheim+Palace+Woodstock), where Churchill was born; [Bibury](https://www.google.com/maps/search/?api=1&query=Bibury), 25 minutes from the hotel; or lunch further north at [Daylesford](https://www.google.com/maps/search/?api=1&query=Daylesford+Organic+Farm+Kingham) or [Quince & Clover](https://www.google.com/maps/search/?api=1&query=Quince+and+Clover+Chipping+Norton). Many village kitchens close on Sunday night, so book dinner ahead: [The Wild Rabbit](https://www.google.com/maps/search/?api=1&query=The+Wild+Rabbit+Kingham) in Kingham, [The Old Butcher's](https://www.google.com/maps/search/?api=1&query=The+Old+Butchers+Stow+on+the+Wold) in Stow, or the hotel.$q$ where id = 477;

-- day 5
update koji_stops set body_md = $q$Check out and head to London. Either return the rental near [Paddington](https://www.google.com/maps/search/?api=1&query=Paddington+Station+London), or take a 10-minute taxi to [Stroud](https://www.google.com/maps/search/?api=1&query=Stroud+Railway+Station) and the direct train to Paddington (~1h30). Aim to reach the London hotel by about 1pm and drop bags even if rooms aren't ready.$q$ where id = 488;
update koji_stops set body_md = $q$An optional swap for this afternoon. The Northern line runs to [Hampstead](https://www.google.com/maps/search/?api=1&query=Hampstead+London) in about 25 minutes; the village sits on the hill above Hampstead Heath. Lunch at [The Holly Bush](https://www.google.com/maps/search/?api=1&query=The+Holly+Bush+Hampstead) or [The Horseshoe](https://www.google.com/maps/search/?api=1&query=The+Horseshoe+Hampstead+London), then the [Antique & Craft Emporium](https://www.google.com/maps/search/?api=1&query=Hampstead+Antique+and+Craft+Emporium), [St John-at-Hampstead](https://www.google.com/maps/search/?api=1&query=St+John+at+Hampstead+Church) and its churchyard (John Constable is buried there), and coffee at [Gail's](https://www.google.com/maps/search/?api=1&query=Gails+Bakery+Hampstead), the original branch. Leave by **4:10** for Evensong; both afternoons meet at the Abbey by 4:40. Otherwise carry on with the plan below.$q$ where id = 493;
update koji_stops set body_md = $q$A sit-down pub lunch near Parliament Square: pies, fish and chips, a pint. [The Red Lion](https://www.google.com/maps/search/?api=1&query=The+Red+Lion+Parliament+Street+London) on Parliament Street has been a pub since the 1800s and sits between Downing Street and the Houses of Parliament, which is why it fills with civil servants and MPs.$q$ where id = 145;
update koji_stops set body_md = $q$October foliage, the lake, and the resident pelicans, which have lived in [St James's Park](https://www.google.com/maps/search/?api=1&query=St+Jamess+Park+London) since a Russian ambassador gave the first ones to Charles II in 1664. Walk on toward [Buckingham Palace](https://www.google.com/maps/search/?api=1&query=Buckingham+Palace+London) at the far end if there's energy for it.$q$ where id = 146;
update koji_stops set body_md = $q$Arrival-day rest at the hotel. Tea or a nap. Regroup at 4:45.$q$ where id = 147;
update koji_stops set body_md = $q$Free, no ticket; queue at the North Door 20 minutes early. A 45-minute sung service by the [Westminster Abbey](https://www.google.com/maps/search/?api=1&query=Westminster+Abbey+London) choir, and a first look inside before tomorrow's full visit. **Mon-Fri 5pm.**$q$ where id = 148;
update koji_stops set body_md = $q$**British:** [The Guinea Grill](https://www.google.com/maps/search/?api=1&query=The+Guinea+Grill+Mayfair+London), a Mayfair pub dating to the 1600s, known for dry-aged British beef and its steak and kidney pie. *Reservation required.*<br><br>**Indian:** [Kricket Soho](https://www.google.com/maps/search/?api=1&query=Kricket+Soho+London), small plates and a tandoor, with walk-ins at the bar before 7pm. *Reservation recommended.*<br><br>**Modern European:** [Sketch (The Glade)](https://www.google.com/maps/search/?api=1&query=Sketch+Mayfair+London), the forest-themed dining room at Sketch in Mayfair, on the list for the birthday itself. *Reservation required; book 4+ weeks ahead.*$q$ where id = 149;

-- day 6
update koji_stops set body_md = $q$The coronation church since 1066 and the burial place of monarchs, with Gothic vaulting and Poets' Corner. About 90 minutes; wander first, then turn on the audio guide. Book the **first timed slot (9:30-10:00)**, the quietest of the day. **Reservation required**; book timed entry 3+ weeks ahead at [Westminster Abbey](https://www.google.com/maps/search/?api=1&query=Westminster+Abbey+London). [Westminster Pier](https://www.google.com/maps/search/?api=1&query=Westminster+Pier+London) is a 5-minute walk, and the boat leaves from there.$q$ where id = 144;
update koji_stops set body_md = $q$About 50 minutes by river from [Westminster Pier](https://www.google.com/maps/search/?api=1&query=Westminster+Pier+London) to [Greenwich Pier](https://www.google.com/maps/search/?api=1&query=Greenwich+Pier+London), passing the London Eye, St Paul's, the Tower, and Tower Bridge on the way. Buy tickets in the Uber app (Uber Boat by Thames Clippers) and sit on the open top deck.$q$ where id = 170;
update koji_stops set body_md = $q$A covered market under a Victorian glass roof, with craft stalls and food stalls from a dozen or more cuisines. Lunch is here. **Most stalls are closed Mondays.** [Greenwich Market](https://www.google.com/maps/search/?api=1&query=Greenwich+Market+London).$q$ where id = 172;
update koji_stops set body_md = $q$A 40,000-square-foot painted ceiling and walls by James Thornhill, completed over 19 years in the early 1700s, in the dining hall of what was the Royal Hospital for Seamen. About 45 minutes. [Old Royal Naval College](https://www.google.com/maps/search/?api=1&query=Old+Royal+Naval+College+Greenwich).$q$ where id = 171;
update koji_stops set body_md = $q$The Prime Meridian runs through the courtyard; stand with a foot in each hemisphere. The walk up through [Greenwich Park](https://www.google.com/maps/search/?api=1&query=Greenwich+Park+London) takes about 10 minutes from the market, and the top looks back over the river to the City. [Royal Observatory Greenwich](https://www.google.com/maps/search/?api=1&query=Royal+Observatory+Greenwich+London).$q$ where id = 173;
update koji_stops set body_md = $q$A 19th-century tea clipper, once the fastest ship on the China tea run, dry-docked and open to walk through. 30 minutes, and easy to skip if anyone is tired. [Cutty Sark](https://www.google.com/maps/search/?api=1&query=Cutty+Sark+Greenwich+London). The [National Maritime Museum](https://www.google.com/maps/search/?api=1&query=National+Maritime+Museum+Greenwich) (free) is the wet-weather alternative.$q$ where id = 174;
update koji_stops set body_md = $q$Same route back, in evening light.$q$ where id = 175;
update koji_stops set body_md = $q$**Fish and chips:** [The Golden Hind](https://www.google.com/maps/search/?api=1&query=The+Golden+Hind+Marylebone+London) in Marylebone, a chippy since 1914, bring your own bottle. *Walk-in fine.*<br><br>**Ethiopian:** [Adulis](https://www.google.com/maps/search/?api=1&query=Adulis+Restaurant+Vauxhall+London) in Vauxhall, Ethiopian and Eritrean platters served on injera and eaten by hand, which suits a table of five. *Reservation recommended.*<br><br>**Japanese:** [Roketsu](https://www.google.com/maps/search/?api=1&query=Roketsu+Marylebone+London) in Marylebone, a Michelin-starred kaiseki counter and the expensive option on the list. *Reservation required; books 6+ weeks out.*$q$ where id = 176;

-- day 7
update koji_stops set body_md = $q$A UNESCO World Heritage site with the largest botanical collection in the world. 30 minutes by Tube from central London (District line to Kew Gardens). The [Palm House](https://www.google.com/maps/search/?api=1&query=Palm+House+Kew+Gardens) is a Victorian glasshouse from 1848, the [Temperate House](https://www.google.com/maps/search/?api=1&query=Temperate+House+Kew+Gardens) is the largest surviving Victorian glasshouse anywhere, and the [Treetop Walkway](https://www.google.com/maps/search/?api=1&query=Treetop+Walkway+Kew+Gardens) runs 18 metres up through the canopy. October means dahlias and autumn colour. Three hours from the 9:30 opening covers it; bring a layer. **Reservation recommended** for timed entry. [Kew Gardens](https://www.google.com/maps/search/?api=1&query=Kew+Gardens+London).$q$ where id = 164;
update koji_stops set body_md = $q$[The Botanical at Kew](https://www.google.com/maps/search/?api=1&query=The+Botanical+Kew+Gardens) inside the gardens, or [The Glasshouse](https://www.google.com/maps/search/?api=1&query=The+Glasshouse+Kew+London) just outside the gate, a Michelin-starred restaurant, so book. Leaving Kew for lunch and coming back costs an hour. Third option: [The Botanist](https://www.google.com/maps/search/?api=1&query=The+Botanist+Kew+Green) on Kew Green.$q$ where id = 165;
update koji_stops set body_md = $q$Free, no tickets. The V&A holds the world's largest collection of decorative arts and design, and it is a straight run from Kew on the District line (about 25 minutes). The fashion and textile galleries connect to Saturday's Liberty stop; the Cast Courts (full-size plaster casts of Trajan's Column and Michelangelo's David) and the jewellery rooms are the other rooms to see. Two hours. The café is in the original 1860s refreshment rooms, the first museum café in the world. [Victoria and Albert Museum](https://www.google.com/maps/search/?api=1&query=Victoria+and+Albert+Museum+London).$q$ where id = 491;
update koji_stops set body_md = $q$15 minutes on the Circle line from South Kensington, or on foot through [Kensington Gardens](https://www.google.com/maps/search/?api=1&query=Kensington+Gardens+London) past the [Serpentine](https://www.google.com/maps/search/?api=1&query=Serpentine+Gallery+London) galleries to [Notting Hill Gate](https://www.google.com/maps/search/?api=1&query=Notting+Hill+Gate+Station+London), about 40 minutes.$q$ where id = 166;
update koji_stops set body_md = $q$Pastel terraces, antiques shops, [Honest Jon's](https://www.google.com/maps/search/?api=1&query=Honest+Jons+Records+Portobello+London) records (a shop here since 1974), and the painted houses on [Lancaster Road](https://www.google.com/maps/search/?api=1&query=Lancaster+Road+Notting+Hill+London). The antiques market runs on Saturdays; a weekday visit is quieter. [Portobello Road](https://www.google.com/maps/search/?api=1&query=Portobello+Road+Notting+Hill+London).$q$ where id = 167;
update koji_stops set body_md = $q$A pub covered in flower baskets, named for Churchill, whose grandparents drank here, with a Thai kitchen in the back that has served food since 1988. [The Churchill Arms](https://www.google.com/maps/search/?api=1&query=The+Churchill+Arms+Notting+Hill+London). For a cocktail first, [Trailer Happiness](https://www.google.com/maps/search/?api=1&query=Trailer+Happiness+Portobello+London) down the road is a tiki bar.$q$ where id = 168;
update koji_stops set body_md = $q$**Nigerian:** [Chuku's](https://www.google.com/maps/search/?api=1&query=Chukus+Tottenham+London) in Tottenham, Nigerian tapas (jollof rice, plantain, goat stew), family-run, about 25 minutes by Tube from Notting Hill. *Reservation required.*<br><br>**West African:** [Akoko](https://www.google.com/maps/search/?api=1&query=Akoko+Fitzrovia+London) in Fitzrovia, a Michelin-starred tasting menu built on West African cooking (smoked jollof, kelewele, suya). The expensive option. *Reservation required; book 4+ weeks ahead.*<br><br>**Caribbean:** [Fish, Wings & Tings](https://www.google.com/maps/search/?api=1&query=Fish+Wings+and+Tings+Brixton+London) in Brixton Village, Trinidadian doubles, jerk wings, and curry goat roti at a counter. *Walk-in fine.*$q$ where id = 169;

-- day 8
update koji_stops set body_md = $q$Free, no tickets; arrive at the 10am opening. The architect John Soane's house, kept as he arranged it under an 1833 Act of Parliament: antiquities, the sarcophagus of Seti I, and Hogarth's A Rake's Progress hung on hinged panels. About 90 minutes. **Closed Mon and Tue.** Open Wed-Sun, 10am-5pm, last admission 4:30pm. [Sir John Soane's Museum](https://www.google.com/maps/search/?api=1&query=Sir+John+Soanes+Museum+London).$q$ where id = 157;
update koji_stops set body_md = $q$The other half of the morning split. [Imperial War Museum](https://www.google.com/maps/search/?api=1&query=Imperial+War+Museum+London) in Lambeth is free and open daily 10am-6pm. The [Churchill War Rooms](https://www.google.com/maps/search/?api=1&query=Churchill+War+Rooms+London), the underground bunker the war cabinet worked from, is the alternative (timed tickets; book ahead). Meet at [The Lamb](https://www.google.com/maps/search/?api=1&query=The+Lamb+Lambs+Conduit+Street+London) for lunch at 12:30pm.$q$ where id = 484;
update koji_stops set body_md = $q$A Victorian pub on Lamb's Conduit Street with its etched-glass "snob screens" still in place, a short walk from both museum tracks. Order the pies. Lamb's Conduit Street itself, a Georgian street of independent shops, is worth ten minutes before or after. [The Lamb](https://www.google.com/maps/search/?api=1&query=The+Lamb+Lambs+Conduit+Street+London).$q$ where id = 159;
update koji_stops set body_md = $q$Free, no tickets. One room with Magna Carta, the Lindisfarne Gospels, handwritten Beatles lyrics, and Jane Austen's manuscripts. About 45 minutes. [British Library](https://www.google.com/maps/search/?api=1&query=British+Library+London). From there, 10 minutes along the canal to [Word on the Water](https://www.google.com/maps/search/?api=1&query=Word+on+the+Water+Kings+Cross), a bookshop on a 1920s Dutch barge.$q$ where id = 160;
update koji_stops set body_md = $q$An Edwardian bookshop with oak galleries and a skylight, where the books are shelved by country rather than by subject. About 30 minutes. From the British Library it is a 25-minute walk or a short Tube ride. [Daunt Books Marylebone](https://www.google.com/maps/search/?api=1&query=Daunt+Books+Marylebone+London).$q$ where id = 161;
update koji_stops set body_md = $q$Five minutes from Daunt. Afternoon tea in the glass-roofed courtyard of Hertford House, a 1776 townhouse holding the Wallace family's collection of 18th-century French art and armour. Less expensive than the Ritz or Claridge's. **Reservation required; book 4 weeks out.** [The Wallace Collection](https://www.google.com/maps/search/?api=1&query=The+Wallace+Collection+London).$q$ where id = 162;
update koji_stops set body_md = $q$**Italian:** [Lina Stores Marylebone](https://www.google.com/maps/search/?api=1&query=Lina+Stores+Marylebone+London), fresh pasta from the Soho deli that has been trading since 1944, in a green-tiled room. The light option after tea. *Reservation recommended.*<br><br>**Indian:** [Trishna](https://www.google.com/maps/search/?api=1&query=Trishna+Marylebone+London), Michelin-starred coastal Indian cooking, known for its Dorset brown crab. *Reservation required.*<br><br>**Modern British:** [The Wigmore](https://www.google.com/maps/search/?api=1&query=The+Wigmore+Langham+London) at The Langham, pub food from Michel Roux Jr's kitchen, with large pies for sharing. *Reservation recommended.*$q$ where id = 163;

-- day 9
update koji_stops set body_md = $q$The Yeoman Warder ("Beefeater") tours leave every 30 minutes from inside the gate and are included with admission: an hour of stories at an easy pace. See the Crown Jewels straight after, before the queue builds. Book the 9am opening slot. **Reservation required.** [Tower of London](https://www.google.com/maps/search/?api=1&query=Tower+of+London).$q$ where id = 150;
update koji_stops set body_md = $q$10 minutes on foot, with views of the Tower and up the river from the middle. The paid glass-floor walkway is skippable. [Tower Bridge](https://www.google.com/maps/search/?api=1&query=Tower+Bridge+London).$q$ where id = 151;
update koji_stops set body_md = $q$London's oldest food market, trading on this site since the 13th century. Lunch works stall by stall rather than as one sit-down: [Bread Ahead](https://www.google.com/maps/search/?api=1&query=Bread+Ahead+Borough+Market+London) doughnuts, [Padella](https://www.google.com/maps/search/?api=1&query=Padella+Borough+Market+London) pasta (if the line is short), a [Kappacasein](https://www.google.com/maps/search/?api=1&query=Kappacasein+Borough+Market+London) cheese toastie, oysters from [Richard Haward's](https://www.google.com/maps/search/?api=1&query=Richard+Hawards+Oysters+Borough+Market+London), a family that has farmed oysters in Essex for seven generations. Eat outside by [Southwark Cathedral](https://www.google.com/maps/search/?api=1&query=Southwark+Cathedral+London). Allow 90 minutes. Since this is the big meal of the day, dinner is kept casual. **Closed Sundays.** [Borough Market](https://www.google.com/maps/search/?api=1&query=Borough+Market+London).$q$ where id = 152;
update koji_stops set body_md = $q$Wren's cathedral, finished in 1710 after the Great Fire. The Whispering Gallery is 257 steps up and the Golden Gallery at the top is 528; nobody has to do the whole climb. Wellington and Nelson are in the crypt. About an hour. **Closed Sundays for sightseeing.** [St Paul's Cathedral](https://www.google.com/maps/search/?api=1&query=St+Pauls+Cathedral+London).$q$ where id = 153;
update koji_stops set body_md = $q$A 5-minute walk from St Paul's. A Victorian arcade of iron and glass from 1881, on the site of the Roman forum; it stood in for Diagon Alley in the first Harry Potter film. 15 minutes. [Leadenhall Market](https://www.google.com/maps/search/?api=1&query=Leadenhall+Market+London).$q$ where id = 154;
update koji_stops set body_md = $q$Ten minutes' walk from Leadenhall. [Old Spitalfields Market](https://www.google.com/maps/search/?api=1&query=Old+Spitalfields+Market+London), the streets around [Brick Lane](https://www.google.com/maps/search/?api=1&query=Brick+Lane+London), vintage shops toward [Shoreditch](https://www.google.com/maps/search/?api=1&query=Shoreditch+London), or the free [Museum of the Home](https://www.google.com/maps/search/?api=1&query=Museum+of+the+Home+London) in Hoxton, set in 18th-century almshouses. Anyone who would rather have tea can peel off to [Fortnum & Mason](https://www.google.com/maps/search/?api=1&query=Fortnum+and+Mason+London); regroup for dinner at 7.$q$ where id = 155;
update koji_stops set body_md = $q$**British:** [St. John Bread and Wine](https://www.google.com/maps/search/?api=1&query=St+John+Bread+and+Wine+Spitalfields+London) in Spitalfields, Fergus Henderson's smaller restaurant: roast bone marrow, Welsh rarebit, Eccles cakes. *Reservation required; book 4+ weeks ahead.*<br><br>**Fish and chips:** [Poppie's](https://www.google.com/maps/search/?api=1&query=Poppies+Fish+and+Chips+Spitalfields) in Spitalfields, a chippy done up like the 1950s. *Walk-in fine.*<br><br>**Indian:** [Brigadiers](https://www.google.com/maps/search/?api=1&query=Brigadiers+Restaurant+London) in the City, Indian barbecue in a room styled on an army mess, ten minutes back toward the hotel. *Reservation required.*<br><br>Afterwards, a nightcap around Shoreditch for anyone still going.$q$ where id = 156;

-- day 10
update koji_stops set body_md = $q$The Making of Harry Potter: the original sets, props, and costumes at [Warner Bros. Studio Tour London](https://www.google.com/maps/search/?api=1&query=Warner+Bros+Studio+Tour+London+Leavesden) in Leavesden, where all eight films were made. All five go. Train from [Euston](https://www.google.com/maps/search/?api=1&query=London+Euston+Station) to [Watford Junction](https://www.google.com/maps/search/?api=1&query=Watford+Junction+Station) (20 minutes) plus the shuttle bus; plan on about 3.5 hours inside and be back in town for Liberty at 4pm. **Timed tickets only; book well ahead.** October Saturdays sell out.$q$ where id = 479;
update koji_stops set body_md = $q$A Tudor-revival department store on Great Marlborough Street, built in the 1920s from the timbers of two decommissioned warships, HMS Impregnable and HMS Hindustan. The Liberty print fabrics and the haberdashery floor are the reason for the stop; the rest of the store is open to wander. No booking; open into the evening. [Liberty London](https://www.google.com/maps/search/?api=1&query=Liberty+London+Great+Marlborough+Street).$q$ where id = 489;
update koji_stops set body_md = $q$Last night with all five together. Nothing booked yet; keep it close to the hotel since Mom leaves early. A Saturday night means booking ahead.$q$ where id = 480;

-- day 11
update koji_stops set body_md = $q$Delta 17 departs at **11:20am** (a schedule change from 1:00pm). Be at [Heathrow Airport](https://www.google.com/maps/search/?api=1&query=Heathrow+Airport+London) by about 8:20am, which means leaving the hotel around 7:45am on the Heathrow Express.$q$ where id = 481;
update koji_stops set body_md = $q$United 935 departs at **3:20pm**; be at [Heathrow Airport](https://www.google.com/maps/search/?api=1&query=Heathrow+Airport+London) by about 12:20pm.$q$ where id = 482;
update koji_stops set body_md = $q$Virgin Atlantic 23 departs at **5:05pm**; be at [Heathrow Airport](https://www.google.com/maps/search/?api=1&query=Heathrow+Airport+London) by about 2:00pm.$q$ where id = 483;

commit;
